### ISSUE TITLE
Fold FastLinq package into this one?

### ISSUE THREAD

**Issue by ndrwrbgs** [jackmott/LinqFaster#26]
Hey @jackmott,

I starred this repo a while ago when I made https://github.com/ndrwrbgs/FastLinq as it was the most popular alternative. It's possible for both libraries to exist concurrently, but their goals are so similar that I'd be interested in offering 1 solution.

If you have some time, could you look over the ReadMe.md, which explains the theory behind the optimizations I made (specifically avoiding IEnumerable information loss) [or check out the milestones for the planned work https://github.com/ndrwrbgs/FastLinq/milestones] and if you think
* The overlap is enough to conflate packages
* The overlap is only in the goal, but the approaches are different enough to keep separate

This will help me to know where to invest in the future :)

Note that the note at the top is related to https://github.com/dotnet/BenchmarkDotNet/issues/155

Thanks!

**Comment by jackmott** [comment]
I think the key thing that makes them different enough to not combine is that FastLinq appears to maintain the lazy evaluation properties of regular Linq, while LinqFaster does away with lazy evaluation in exchange for raw performance. Instead offering workarounds for common patters like "whereselect" for example.

Also keep an eye on some of the latest .NET Core optimizations, since they are doing some similar things to you, I believe.

**Comment by ndrwrbgs** [comment]
> Also keep an eye on some of the latest .NET Core optimizations, since they are doing some similar things to you, I believe

They definitely are, but I work at a big company that likes to use old technology, so my team won't be getting those any time soon :( Fortunately, those .NET optimizations are being influenced by projects like ours :)

Thanks for your feedback, we'll continue as separate optimization tracks!
