### ISSUE TITLE
any reason you use F postfix?

### ISSUE THREAD

**Issue by friuns2** [jackmott/LinqFaster#7]
hi, any reason you use F postfix?
would be easier to migrate if methods would be just overriden

**Comment by jackmott** [comment]
Yes, it makes it much easier to use alongside normal Linq, which is often desired.  In some cases results wouldn't even be the same if you just swapped in the methods, since Linq is lazily evaluated.  For instance a Where().Select() in Linq would need to be translated to WhereSelectF in LinqFaster to maintain the same semantics (and get the best performance)
